### ISSUE TITLE
Move to TypeScript

### ISSUE THREAD

**Issue by dkundel** [twilio-labs/actions-sms#3]
The current GitHub Action is written in JavaScript. All dependencies support TypeScript and we should just move this project to TypeScript to have some additional type safety.

**Comment by palaparthi** [comment]
Can I take this up?

**Comment by dkundel** [comment]
Absolutely!

**Comment by palaparthi** [comment]
I get permission denied error when I try to push a branch

**Comment by dkundel** [comment]
You'll have to create a fork and then push your branch to that fork instead.

https://help.github.com/en/articles/fork-a-repo

**Comment by palaparthi** [comment]
Thanks! Can you review the pull request.

**Comment by palaparthi** [comment]
Thanks for approving my first open source PR! let me know if I can help with any other open issues.

**Comment by dkundel** [comment]
Thank you for contributing to the project and incorporating all the feedback so quickly! We'd love to see if we can potentially send you some swag. You can find more information here: https://twil.io/hacktoberfest-swag
